// Drill library. `src` credits the coach, program or player a drill comes from.
// needs: equipment beyond a ball — "hoop", "weights", "partner" (partner or team)

export const CATEGORIES = {
  shooting: { label: "Shooting" },
  handles: { label: "Ball Handling" },
  finishing: { label: "Finishing" },
  post: { label: "Post & Footwork" },
  defense: { label: "Defense" },
  strength: { label: "Strength" },
  vertical: { label: "Vertical" },
  speed: { label: "Speed & Agility" },
  conditioning: { label: "Conditioning" },
  mobility: { label: "Mobility" },
  recovery: { label: "Active Recovery" },
};

export const DRILLS = [
  // ---------- Shooting ----------
  { id: "set-lifts", cat: "shooting", name: "Set Lifts", minutes: 5, level: 1, positions: [], needs: ["hoop"],
    src: "Villanova (Jay Wright)",
    how: "3–5 ft from the rim, ball in one hand. Bend your knees, get your elbow under the ball and lift it into a one-motion follow-through. Villanova players did these every day before practice to groove technique. 3 sets of 10 makes." },
  { id: "get-50", cat: "shooting", name: "Get 50", minutes: 8, level: 1, positions: [], needs: ["hoop"],
    src: "Villanova (Jay Wright)",
    how: "Without stopping: 10 set lifts, 10 Mikans, 10 reverse Mikans, 10 Bradleys, then 10 1-2 step shots from the top of the key. Fifty makes, all with your elbow under the ball." },
  { id: "bradleys", cat: "shooting", name: "Bradleys", minutes: 5, level: 1, positions: [], needs: ["hoop"],
    src: "Villanova (Jay Wright)",
    how: "From 5–6 ft, take a little hop into your shot and release on the way up with your elbow as high as it goes. The closer to the rim, the higher the release. Sets of 5 from each side, 4 rounds." },
  { id: "kobe-ladder", cat: "shooting", name: "Kobe's Pregame Ladder", minutes: 20, level: 2, positions: [], needs: ["hoop"],
    src: "Kobe Bryant pregame routine",
    how: "Kobe started under the rim (15–20 makes each hand), moved to 15 ft along each baseline, wing and the free throw line (15–20 makes per spot), then threes from the corners, wings and top (10–20 makes per spot). Scaled version: 10 makes per spot, every spot." },
  { id: "ray-allen", cat: "shooting", name: "Ray Allen Game-Shot Session", minutes: 15, level: 2, positions: ["SG", "SF"], needs: ["hoop"],
    src: "Ray Allen pregame routine",
    how: "Start with free throws focused only on your release. Then shoot every shot you actually take in games: catch-and-shoot off a screen, one-dribble pull-ups, spot-ups. Ray went for about 200 shots an hour. Shoot from your legs and jump in one motion. Goal: 70 game-speed shots." },
  { id: "kd-freeze", cat: "shooting", name: "KD Freeze Pull-Up", minutes: 8, level: 2, positions: ["SG", "SF", "PF"], needs: ["hoop"],
    src: "Kevin Durant scoring workout",
    how: "Three stationary changes of direction to set up the defender, then a quick between-the-legs into a freeze pull-up. Go from both elbows and both wings. 8 makes per spot." },
  { id: "hanlen-slice", cat: "shooting", name: "Retreat Drag into Slice Pull-Up", minutes: 8, level: 3, positions: ["PG", "SG"], needs: ["hoop"],
    src: "Drew Hanlen (Pure Sweat)",
    how: "Use a chair as the screen. Retreat dribble, drag the ball back, then slice tight off the screen into a mid-range pull-up. Both directions, 3 sets of 6." },
  { id: "form", cat: "shooting", name: "Form Shooting", minutes: 5, level: 1, positions: [], needs: ["hoop"],
    src: "Fundamental",
    how: "One hand, 3 ft from the rim. Make 10 at each of 5 spots, step back a foot, repeat. Hold your follow-through every time." },
  { id: "bed-shots", cat: "shooting", name: "Lying Form Shots", minutes: 4, level: 1, positions: [], needs: [],
    src: "Fundamental (no hoop needed)",
    how: "Lie on your back and shoot the ball straight up so it lands back in your shooting hand. Backspin, elbow in, snap the wrist. 3 sets of 25." },
  { id: "free-throws", cat: "shooting", name: "Free Throw Pressure Set", minutes: 5, level: 1, positions: [], needs: ["hoop"],
    src: "Fundamental",
    how: "Shoot 2 at a time, 20 total, with a short sprint between pairs so you shoot tired. Log your makes. Stanford players improved their free throws by about 9% after extending their sleep, so get your rest too." },
  { id: "spot-up", cat: "shooting", name: "5-Spot Catch & Shoot", minutes: 8, level: 1, positions: ["SG", "SF", "PF"], needs: ["hoop"],
    src: "Fundamental",
    how: "Corners, wings and top. Self-pass with backspin, step into it, 10 shots per spot. Track makes." },
  { id: "game-circuit", cat: "shooting", name: "Game-Speed Shot Circuit", minutes: 10, level: 3, positions: [], needs: ["hoop"],
    src: "Fundamental",
    how: "Ten spots, one shot each, sprint between spots. 5 rounds. Shoot under fatigue like it's the fourth quarter." },

  // ---------- Ball handling ----------
  { id: "curry-two-ball", cat: "handles", name: "Curry Two-Ball Series", minutes: 8, level: 2, positions: ["PG", "SG", "SF"], needs: [],
    src: "Stephen Curry & Brandon Payne",
    how: "Curry opens his workouts with 15–20 minutes of two-ball dribbling before he shoots. 45 s each: together, alternating, high-low, side-to-side, then crossovers with both balls. Fight to keep both alive." },
  { id: "tennis-overload", cat: "handles", name: "Tennis Ball Overload", minutes: 5, level: 2, positions: ["PG", "SG"], needs: [],
    src: "Brandon Payne (Accelerate Basketball)",
    how: "Dribble with one hand while tossing and catching a tennis ball with the other. Payne calls this overload: making the brain process more so the game feels slower. Switch hands every 30 s. Advanced: have a partner toss the tennis ball at random." },
  { id: "brickley-weighted", cat: "handles", name: "Heavy-Ball Stationary Series", minutes: 6, level: 1, positions: [], needs: [],
    src: "Chris Brickley",
    how: "Use a heavier ball if you have one. Inside-outs, side-to-sides, between the legs and behind the back, 30 s each. Then repeat with a regular ball and feel how light it is." },
  { id: "brickley-3level", cat: "handles", name: "Three-Level Combo", minutes: 6, level: 2, positions: [], needs: [],
    src: "Chris Brickley",
    how: "Pick a 3-move combo (for example cross, between, behind). Run it at knee height, then waist, then chest, 30 s each, without stopping. 3 rounds." },
  { id: "kyrie-counters", cat: "handles", name: "Kyrie Counter Combos", minutes: 8, level: 2, positions: ["PG", "SG", "SF"], needs: [],
    src: "Kyrie Irving",
    how: "Kyrie learns a move, then the counter, then the counter to that. Low crossover → in-and-out → hesitation → behind-the-back wrap, then attack the space. 6 chains each direction at game speed." },
  { id: "calipari-attack", cat: "handles", name: "Dribble-Drive Attack Series", minutes: 8, level: 2, positions: ["PG", "SG", "SF"], needs: ["hoop"],
    src: "Kentucky (John Calipari)",
    how: "From the top and both wings, attack a gap with 1–2 hard dribbles and either finish at the rim or jump-stop and kick to a target. Work on push-pull ball quickness. 4 reps per spot, both hands." },
  { id: "pound", cat: "handles", name: "Stationary Pound Dribbles", minutes: 4, level: 1, positions: [], needs: [],
    src: "Fundamental",
    how: "30 s each hand: hard low pounds, then waist-high, then shoulder-high. Eyes up." },
  { id: "figure8", cat: "handles", name: "Figure-8 Dribble", minutes: 3, level: 1, positions: [], needs: [],
    src: "Fundamental",
    how: "Dribble around and through your legs in a figure-8. Stay low, 3 × 45 s." },
  { id: "crossover-series", cat: "handles", name: "Crossover Series", minutes: 5, level: 1, positions: [], needs: [],
    src: "Fundamental",
    how: "Crossover, between-the-legs, behind-the-back: 10 of each in both directions, low and hard. Eyes up." },
  { id: "spider", cat: "handles", name: "Spider Dribble", minutes: 3, level: 1, positions: [], needs: [],
    src: "Fundamental",
    how: "Ball between your feet: right hand front, left hand front, right hand back, left hand back. Quick fingertip taps, 4 × 30 s." },
  { id: "wall-dribble", cat: "handles", name: "Wall Dribbles", minutes: 3, level: 1, positions: [], needs: [],
    src: "Fundamental",
    how: "Arm straight overhead, dribble against a wall with your fingertips. 30 s each hand, 3 rounds. Builds hand and forearm strength." },
  { id: "cone-attack", cat: "handles", name: "Cone Attack Combos", minutes: 6, level: 2, positions: ["PG", "SG", "SF"], needs: [],
    src: "Fundamental",
    how: "5 cones 6 ft apart. A different move at each cone, explode out of every move. 8 trips." },

  // ---------- Finishing ----------
  { id: "mikan", cat: "finishing", name: "Mikan Drill", minutes: 4, level: 1, positions: [], needs: ["hoop"],
    src: "George Mikan & coach Ray Meyer (DePaul)",
    how: "Meyer built this for Mikan at DePaul. From under the rim: right-hand layup, catch it out of the net, left-hand layup, and keep alternating without the ball touching the floor. 3 × 60 s." },
  { id: "kyrie-mikans", cat: "finishing", name: "Kyrie Mikan Variations", minutes: 6, level: 2, positions: ["PG", "SG", "SF"], needs: ["hoop"],
    src: "Kyrie Irving",
    how: "Mikan drill with variations: reverse Mikans, high-glass finishes, off one foot, inside-hand finishes, then underhand scoops. 30 s per variation." },
  { id: "hanlen-prohop", cat: "finishing", name: "Pro Hop Finishes", minutes: 6, level: 2, positions: ["PG", "SG", "SF"], needs: ["hoop"],
    src: "Drew Hanlen (Pure Sweat)",
    how: "Put a chair in the lane as the rim protector. Drive at it and pro hop (a jump stop that changes direction) past it to finish. Both directions, 8 makes each." },
  { id: "hanlen-ride", cat: "finishing", name: "Defender-on-the-Side Layups", minutes: 6, level: 2, positions: [], needs: ["hoop", "partner"],
    src: "Drew Hanlen (Pure Sweat)",
    how: "A partner rides your hip as you drive. Use an arm bar to protect the ball, absorb the contact and finish high off the glass. 10 each side." },
  { id: "euro", cat: "finishing", name: "Euro Step & Reverse Finishes", minutes: 6, level: 2, positions: ["PG", "SG", "SF"], needs: ["hoop"],
    src: "Fundamental",
    how: "From the wing: euro steps and reverse layups. 6 makes each, both hands." },

  // ---------- Post & footwork ----------
  { id: "newell-footwork", cat: "post", name: "Big Man Camp Footwork", minutes: 8, level: 1, positions: ["PF", "C"], needs: ["hoop"],
    src: "Pete Newell's Big Man Camp",
    how: "Newell's camp taught post footwork to Hakeem, Walton, Worthy and more. Catch on the block, then drop step baseline, drop step middle, jump hook, and up-and-under. 6 each side." },
  { id: "dream-shake", cat: "post", name: "Dream Shake Mirror Drill", minutes: 6, level: 2, positions: ["PF", "C", "SF"], needs: [],
    src: "Hakeem Olajuwon",
    how: "Hakeem said the Dream Shake came from soccer footwork. In front of a mirror: shoulder fake, spin, pump fake, step-through, staying balanced. 3 × 10 on each pivot foot, then take it to the block." },
  { id: "dirk-fade", cat: "post", name: "One-Leg Fadeaway", minutes: 6, level: 3, positions: ["SF", "PF", "C"], needs: ["hoop"],
    src: "Dirk Nowitzki & Holger Geschwindner",
    how: "Geschwindner's rule: the minimum effort for the shot is one step. From the mid-post: one step, turn, line up knee and elbow, fade off one leg. 3 × 8 over each shoulder." },
  { id: "jab-series", cat: "post", name: "Triple Threat Jab Series", minutes: 5, level: 1, positions: ["SG", "SF", "PF"], needs: ["hoop"],
    src: "Fundamental",
    how: "Jab and shoot, jab and drive, jab and cross over. 10 each, both pivot feet." },
  { id: "ladder", cat: "speed", name: "Agility Ladder", minutes: 5, level: 1, positions: [], needs: [],
    src: "Fundamental",
    how: "In-in-out-out, lateral shuffle, icky shuffle. 3 trips each, quick light feet. Chalk lines work if you don't have a ladder." },

  // ---------- Defense ----------
  { id: "izzo-war", cat: "defense", name: "War Rebounding Drill", minutes: 8, level: 2, positions: [], needs: ["hoop", "partner"],
    src: "Michigan State (Tom Izzo)",
    how: "Izzo's signature: 5-on-5 (or 2-on-2) with one ball. Shot goes up, everyone boxes out and fights for the board, then the winner outlets and runs. Solo version: throw it high off the glass, chin it with two hands, pivot and outlet. 3 × 2 min." },
  { id: "duke-shell", cat: "defense", name: "4-on-4 Shell", minutes: 10, level: 2, positions: [], needs: ["partner"],
    src: "Duke (Mike Krzyzewski)",
    how: "4 offense pass around the perimeter. Defense closes out, jumps to help on every pass, stunts on drives and talks the whole time. Duke runs it to keep players in a stance for an entire possession." },
  { id: "closeout-slide", cat: "defense", name: "Closeout, Slide, Recover", minutes: 5, level: 1, positions: [], needs: [],
    src: "Solo version of shell closeouts",
    how: "Sprint to a cone, chop your feet into a closeout with hands high, slide 3 steps each way, sprint back to the paint. 8 reps." },
  { id: "zig-zag", cat: "defense", name: "Zig-Zag Slides", minutes: 5, level: 1, positions: [], needs: [],
    src: "Fundamental",
    how: "Slide diagonally baseline to baseline, drop step at each sideline turn. Stay low, never click your heels. 4 trips." },

  // ---------- Strength ----------
  { id: "goblet-squat", cat: "strength", name: "Goblet Squats", minutes: 6, level: 1, positions: [], needs: ["weights"],
    src: "Strength & conditioning staple",
    how: "4 × 10. Dumbbell at your chest, sit between your heels, drive up through the whole foot." },
  { id: "split-squat", cat: "strength", name: "Bulgarian Split Squats", minutes: 7, level: 2, positions: [], needs: [],
    src: "Strength & conditioning staple",
    how: "3 × 8 each leg, back foot on a bench. Hold dumbbells if you have them. Builds single-leg power for jumping off one foot." },
  { id: "rdl", cat: "strength", name: "Romanian Deadlifts", minutes: 6, level: 2, positions: [], needs: ["weights"],
    src: "Strength & conditioning staple",
    how: "4 × 8. Soft knees, hips back, flat back. Strong hamstrings protect your knees when you land." },
  { id: "nordics", cat: "strength", name: "Nordic Hamstring Curls", minutes: 5, level: 2, positions: [], needs: [],
    src: "Injury-prevention research staple",
    how: "Kneel with your ankles anchored. Lower your body forward as slowly as you can, catch yourself, push back up. 3 × 5. One of the best-studied hamstring injury-prevention exercises." },
  { id: "copenhagen", cat: "strength", name: "Copenhagen Side Plank", minutes: 4, level: 2, positions: [], needs: [],
    src: "Injury-prevention research staple",
    how: "Side plank with your top leg on a bench. 3 × 20 s each side. Strengthens the groin for cutting." },
  { id: "pushups", cat: "strength", name: "Push-Up Ladder", minutes: 5, level: 1, positions: [], needs: [],
    src: "Bodyweight staple",
    how: "3 rounds: 10 regular, 8 wide, 6 close-grip. 45 s rest." },
  { id: "core", cat: "strength", name: "Core Circuit", minutes: 6, level: 1, positions: [], needs: [],
    src: "Bodyweight staple",
    how: "Plank 45 s, side plank 30 s each side, dead bugs × 12, hollow hold 30 s. 2 rounds." },
  { id: "pullups", cat: "strength", name: "Pull-Ups / Inverted Rows", minutes: 5, level: 1, positions: ["PF", "C"], needs: [],
    src: "Bodyweight staple",
    how: "4 sets, stopping 1–2 reps before failure. Upper-back strength for rebounding and boxing out." },
  { id: "calf-raises", cat: "strength", name: "Single-Leg Calf Raises", minutes: 4, level: 1, positions: [], needs: [],
    src: "Bodyweight staple",
    how: "3 × 15 each leg off a step, 2 s pause at the top. Strong calves help your ankles and your bounce." },

  // ---------- Vertical ----------
  { id: "box-jumps", cat: "vertical", name: "Box Jumps", minutes: 5, level: 1, positions: [], needs: [],
    src: "Plyometric staple",
    how: "5 × 4. Max effort, land softly, step down. Full rest: quality over quantity." },
  { id: "approach-jumps", cat: "vertical", name: "Approach Jumps", minutes: 5, level: 1, positions: [], needs: [],
    src: "Plyometric staple",
    how: "3-step approach, touch as high as you can. 3 × 5 off two feet, 3 × 5 off one foot." },
  { id: "depth-jumps", cat: "vertical", name: "Depth Jumps", minutes: 5, level: 3, positions: [], needs: [],
    src: "Plyometric staple",
    how: "Step off a 12–18 in box, land and jump instantly. 4 × 4. Keep ground contact short." },
  { id: "pogo", cat: "vertical", name: "Pogo Hops", minutes: 3, level: 1, positions: [], needs: [],
    src: "Plyometric staple",
    how: "Stiff ankles, quick bounces off the balls of your feet. 3 × 20 s." },
  { id: "broad-jumps", cat: "vertical", name: "Broad Jumps", minutes: 4, level: 1, positions: [], needs: [],
    src: "Plyometric staple",
    how: "4 × 3. Swing the arms, explode forward, stick the landing for 2 s." },
  { id: "tip-drill", cat: "vertical", name: "Rim Tip Drill", minutes: 4, level: 2, positions: ["PF", "C"], needs: ["hoop"],
    src: "Fundamental",
    how: "Tip the ball off the backboard nonstop for 30 s, 4 rounds. Builds second-jump quickness." },

  // ---------- Speed & agility ----------
  { id: "lane-agility", cat: "speed", name: "Lane Agility Test", minutes: 6, level: 1, positions: [], needs: [],
    src: "NBA Draft Combine",
    how: "The combine drill: sprint up the lane line, defensive slide across the baseline, backpedal up the other line, slide back across, then reverse it. 4 timed runs with full rest. Log your best time." },
  { id: "three-quarter-sprint", cat: "speed", name: "3/4-Court Sprint", minutes: 5, level: 1, positions: [], needs: [],
    src: "NBA Draft Combine",
    how: "Baseline to the far free throw line, all out. 6 reps, walk back to recover. Log your best time." },
  { id: "shuttle", cat: "speed", name: "Reaction Shuttle", minutes: 5, level: 1, positions: [], needs: [],
    src: "Agility staple",
    how: "Three cones 5 yd apart. Start in the middle, sprint to whichever side a partner (or a random timer) calls. 8 reps." },

  // ---------- Conditioning ----------
  { id: "suicides", cat: "conditioning", name: "Suicide Sprints", minutes: 6, level: 1, positions: [], needs: [],
    src: "Classic",
    how: "Free throw line, half court, far free throw line, baseline, touching each line. 6 reps, 45 s rest." },
  { id: "17s", cat: "conditioning", name: "Sideline 17s", minutes: 6, level: 2, positions: [], needs: [],
    src: "Classic",
    how: "Sideline to sideline 17 times in under 60 s. 90 s rest. 3–4 reps." },
  { id: "full-court-layups", cat: "conditioning", name: "Full-Court Layups", minutes: 5, level: 1, positions: [], needs: ["hoop"],
    src: "Classic",
    how: "Speed-dribble the length of the floor, finish, sprint back. 2 min on, 1 off, 3 rounds." },
  { id: "intervals", cat: "conditioning", name: "Court Intervals", minutes: 8, level: 2, positions: [], needs: [],
    src: "Classic",
    how: "20 s all-out, 40 s jog. 8 rounds. Matches the stop-and-go of a real game." },
  { id: "jump-rope", cat: "conditioning", name: "Jump Rope", minutes: 5, level: 1, positions: [], needs: [],
    src: "Classic",
    how: "5 × 60 s with 20 s rest. Mix two-foot, alternating feet and double-unders." },

  // ---------- Mobility ----------
  { id: "warmup", cat: "mobility", name: "Dynamic Warm-Up", minutes: 6, level: 1, positions: [], needs: [],
    src: "Fundamental",
    how: "High knees, butt kicks, carioca, walking lunges, leg swings, arm circles. Down and back for each." },
  { id: "hip-mobility", cat: "mobility", name: "Hip Mobility Flow", minutes: 5, level: 1, positions: [], needs: [],
    src: "Mobility staple",
    how: "90/90 switches, world's greatest stretch, deep squat hold. Loose hips give you a better first step." },
  { id: "ankle-mobility", cat: "mobility", name: "Ankle Mobility", minutes: 4, level: 1, positions: [], needs: [],
    src: "Mobility staple",
    how: "Knee-to-wall ankle stretch 2 × 10 each side, then toe raises and slow balance holds." },
  { id: "cooldown", cat: "mobility", name: "Cool-Down Stretch", minutes: 5, level: 1, positions: [], needs: [],
    src: "Fundamental",
    how: "Hamstrings, quads, hip flexors, calves, shoulders. 30 s each, slow breathing." },

  // ---------- Active recovery ----------
  { id: "flush", cat: "recovery", name: "Easy Cardio Flush", minutes: 20, level: 1, positions: [], needs: [],
    src: "Active recovery",
    how: "Bike, swim, or brisk walk at an easy pace where you could hold a conversation. Gets blood moving to sore legs without adding fatigue." },
  { id: "foam-roll", cat: "recovery", name: "Foam Roll Circuit", minutes: 10, level: 1, positions: [], needs: [],
    src: "Active recovery",
    how: "60 s each: calves, quads, IT band area, glutes, upper back. Roll slowly and pause on tight spots. No roller? Use a ball or a water bottle." },
  { id: "hooper-yoga", cat: "recovery", name: "Yoga Flow for Hoopers", minutes: 12, level: 1, positions: [], needs: [],
    src: "Active recovery",
    how: "Downward dog, low lunge, pigeon, lizard, child's pose, supine twist. Hold each 45 s and breathe through your nose." },
  { id: "light-form", cat: "recovery", name: "Light Form Shooting", minutes: 10, level: 1, positions: [], needs: ["hoop"],
    src: "Active recovery",
    how: "Close-range form shots with no jumping. Easy reps on a recovery day keep your touch without loading your legs." },
  { id: "band-shoulders", cat: "recovery", name: "Band Shoulder Care", minutes: 6, level: 1, positions: [], needs: [],
    src: "Active recovery",
    how: "Band pull-aparts, external rotations, face pulls. 2 × 15 each. A towel works if you don't have a band." },
  { id: "breathing", cat: "recovery", name: "Box Breathing & Legs Up the Wall", minutes: 6, level: 1, positions: [], needs: [],
    src: "Active recovery",
    how: "Lie with your legs up the wall. Breathe in 4 s, hold 4, out 4, hold 4. Calms your nervous system. Great before bed too." },
];

// Short sources list shown in the app
export const SOURCES = [
  "Villanova shooting drills (Jay Wright): Championship Productions coaching clinics",
  "War rebounding drill (Tom Izzo, Michigan State): Grantland, Coach's Clipboard",
  "Shell drill (Duke, Mike Krzyzewski): Coaching Toolbox, Coach's Clipboard",
  "Pete Newell's Big Man Camp: Wikipedia, Human Kinetics",
  "Mikan drill (George Mikan & Ray Meyer): Wikipedia",
  "Kobe Bryant and Ray Allen pregame routines: ESPN, Bleacher Report",
  "Stephen Curry & Brandon Payne training: ESPN",
  "Kevin Durant scoring workout: Coach's Clipboard",
  "Kyrie Irving ball handling and Mikan variations: Bleacher Report, Breakthrough Basketball",
  "Hakeem Olajuwon Dream Shake: Upper Deck, STACK",
  "Dirk Nowitzki & Holger Geschwindner: ESPN, Dallas Morning News",
  "Drew Hanlen drills: Basketball Immersion",
  "Chris Brickley drills: Wilson",
  "Dribble drive motion (John Calipari): Championship Productions",
  "NBA Draft Combine agility and sprint tests",
  "Sleep extension study (Cheri Mah, Stanford basketball): AASM / SLEEP 2011",
];
